name: Docker Image Build and Publish

on:
  push:
    branches:
      - main  # Executa o workflow sempre que houver push na branch main

jobs:
  build:
    runs-on: ubuntu-latest  # Utiliza a última versão do Ubuntu para rodar os jobs

    steps:
      # Checkout do código-fonte
      - name: Checkout code
        uses: actions/checkout@v2

      # Configura o Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Logar no DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir a imagem Docker
      - name: Build the Docker image
        run: |
          docker build -t edsonsiqueira/api-filmes-node:latest .

      # Publicar a imagem no DockerHub
      - name: Push the Docker image to DockerHub
        run: |
          docker push edsonsiqueira/api-filmes-node:latest

  badge:
    runs-on: ubuntu-latest
    needs: build  # Esse job depende da conclusão do job build

    steps:
      # Checkout do código-fonte
      - name: Checkout code
        uses: actions/checkout@v2

      # Adicionar um badge de status para a imagem Docker no README
      - name: Add Docker Image Badge
        run: |
          badge_url="https://img.shields.io/docker/image-size/edsonsiqueira/api-filmes-node/latest?logo=docker"
          sed -i "/# Badges/a ![Docker Image Size]($badge_url)" README.md

      # Commit das mudanças no README.md
      - name: Commit changes to README
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Adicionando badge da imagem Docker"
          git push
